apiVersion: v1
kind: Secret
metadata:
  name: bdsbusiness-secret
  namespace: default
type: Opaque
stringData:
  DB_ROOT_PASSWORD: rootpassword123
  DB_NAME: bds
  DB_USER: bdsuser
  DB_PASSWORD: bdspassword123
  JWT_SECRET: mon_super_secret_jwt_key_2026